# ==============================================
# Main Inventory File for Chapter 11
# ==============================================
# Update the IP addresses with your actual server IPs

[webservers]
ansible-lab-server-2 ansible_host=34.2.63.201

[dbservers]
#ansible-lab-server-3 ansible_host=34.2.56.133

[production:children]
webservers
dbservers

[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=/Users/rahulwagh/Downloads/ansible-demo/ansible-course-ssh-key
ansible_python_interpreter=/usr/bin/python3
